name: Self-Assign and Add Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  self_assign_and_add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Get issue information
        id: issue_info
        run: |
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "repository=${{ github.repository }}" >> $GITHUB_ENV

      - name: Assign issue to creator
        run: |
          issue_number="${{ github.event.issue.number }}"
          repository="${{ github.repository }}"
          issue_creator="${{ github.event.issue.user.login }}"
          token="${{ secrets.GITHUB_TOKEN }}"
          
          response=$(curl -X POST -H "Authorization: token $token" -d '{"assignees":["'$issue_creator'"]}' "https://api.github.com/repos/$repository/issues/$issue_number/assignees")
          echo "Response: $response"

      - name: Add issue to project
        run: |
          issue_number="${{ github.event.issue.number }}"
          repository="${{ github.repository }}"
          project_id="2"  # Replace with your project ID
          token="${{ secrets.GITHUB_TOKEN }}"
          
          response=$(curl -X POST -H "Authorization: token $token" -d '{"content_id":'$issue_number', "content_type":"Issue"}' "https://api.github.com/projects/$project_id/columns")
          echo "Response: $response"
