name: Auto-Assign Issue to Project and Column

on:
  issues:
    types:
      - opened

jobs:
  auto_assign_and_add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "repository=${{ github.repository }}" >> $GITHUB_ENV
          echo "project_name=KANBAN" >> $GITHUB_ENV
          echo "token=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" >> $GITHUB_ENV

      - name: Assign issue to creator
        run: |
          issue_number="${{ github.event.issue.number }}"
          repository="${{ github.repository }}"
          issue_creator="${{ github.event.issue.user.login }}"
          token="${{ env.token }}"
          
          response=$(curl -X POST -H "Authorization: token $token" -d '{"assignees":["'$issue_creator'"]}' "https://api.github.com/repos/$repository/issues/$issue_number/assignees")
          echo "Response: $response"

      - name: Add issue to project
        run: |
          issue_number="${{ github.event.issue.number }}"
          repository="${{ github.repository }}"
          project_name="${{ env.project_name }}"
          token="${{ env.token }}"
          
          project_id=$(curl -H "Authorization: token $token" "https://api.github.com/repos/$repository/projects" | jq -r '.[] | select(.name == "'$project_name'") | .id')
          
          if [ -z "$project_id" ]; then
            echo "Project not found: $project_name"
            exit 1
          fi
          
          response=$(curl -X POST -H "Authorization: token $token" -d '{"content_id":'$issue_number', "content_type":"Issue"}' "https://api.github.com/projects/$project_id/columns")
          echo "Response: $response"
